### ISSUE TITLE
Implement "draw" function

### ISSUE THREAD

**Issue by gowerc** [insightsengineering/rbmi#1]
## Input

```
draw(
    data = data.frame(...),               # Dataset with all required variables
    vars = list(
        visit = “visit”,                 # Factor J-levels
        group = “arm”,                   # Factor L-levels
        method = “method”                # Character fixed values i.e. MAR, JTR, etc
        subjid = “subjid”,               # Character or factor ?
        response = “response”,           # Numeric continuous
        covariates = c(“c1”, “c2”, “c1*c3”, “base_out*visit”) 
    ),
    data_ice = data.frame(),              
    method = method_obj()                  #  A "method" object
)
```

data:

```
| subjid  |  arm |   visit | response | cov1 | cov2  | igrp |
|----------------------------------------------------|------|
|   1     |   A   |   1    |   10     |  ..  |  ..   |  A   |
|   1     |   A   |   2    |   11     |  ..  |  ..   |  A   |
|   1     |   A   |   3    |          |  ..  |  ..   |  A   |
|   1     |   A   |   4    |   12     |  ..  |  ..   |  A   |
|   2     |   B   |   1    |   10     |  ..  |  ..   |  B   |
|   2     |   B   |   2    |   10     |  ..  |  ..   |  B   |
|   3     |   A   |   1    |   10     |  ..  |  ..   |  C   |
```

data_ice:

```
| subjid |  method  |   visit   | 
|-------------------------------|
|  1     |   CIR    |    3      |
|  3     |   MAR    |    5      | 

```

## Output

```
list(  
    samples = list(
        list(
            "beta" =  c(0.1, 0.2, … ),
            "sigma" = list( "group_label_1" = matrix(...), "group_label_2" = matrix(...) ),
            "index" = c(1,5,2,1,6,2,3)    # subjid index from original dataset
        ),
        list(
            "beta" =  c(0.1, 0.2, … ),
	    "sigma" = list( "arm_A" = matrix(...), "arm_B" = matrix(...) ) ,
	    "index" = c(1,5,2,1,6,2,3) 
	),
	…
    ),
    data = rmData_OBJ()  # an rmData object
)
```

## TODOs

- [x] threshold / error logic
- [x] handling of strategies & mar filtering
- [ ] Summarise mmrm structures used
